# This is a basic workflow to help you get started with Actions

name: Node test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
  
    strategy:
      matrix:
        node-version: [18.x]
        pnpm-version: [8]
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Installing package manager before installing node (must be in this order).
      - uses: pnpm/actions-setup@v2
        with: 
          version: ${{ matrix.pnpm-version }} 
      - uses: actions/setup-node@v3
      # Installing Node environment and specifiying the package manager to use
      - name: Setup environment of NodeJS ${{ matrix.node-version }} 
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      # Installing project dependencies
      - name: Installing dependencies
        run: pnpm install
      # Run all test
      - name: Test code
        run: pnpm test
      
